# Game states
GAME_STATE_ACTIVE = 1
GAME_STATE_PAUSED = 2
GAME_STATE_NOT_READY = 3

# Object status states
STATUS_ACTIVE = 1
STATUS_INACTIVE = 2
STATUS_DIM = 3
STATUS_CUTSCENE = 4

# Prerender status states
PRERENDER_STATUS_DONE = 1
PRERENDER_STATUS_PENDING = 2
PRERENDER_STATUS_READY = 3
